# Generated by Django 5.2.16 on 2026-07-11 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, verbose_name='岗位名称')),
                ('job_level', models.CharField(choices=[('junior', '初级'), ('middle', '中级'), ('senior', '高级'), ('expert', '专家')], default='middle', max_length=20, verbose_name='岗位级别')),
                ('scenario', models.CharField(default='社会招聘', max_length=64, verbose_name='适用场景')),
                ('description', models.TextField(blank=True, verbose_name='岗位描述')),
                ('responsibilities', models.JSONField(default=list, verbose_name='岗位职责')),
                ('requirements', models.JSONField(default=list, verbose_name='任职要求')),
                ('technical_tags', models.JSONField(default=list, verbose_name='技术方向')),
                ('keywords', models.JSONField(default=list, verbose_name='岗位关键词')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('disabled', '停用')], default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.department', verbose_name='所属部门')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_position_templates', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '岗位模板',
                'verbose_name_plural': '岗位模板',
                'ordering': ['-updated_at'],
            },
        ),
    ]
