# Generated by Django 5.2.16 on 2026-07-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_task_resume_nullable_and_parse_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='job_type',
            field=models.CharField(choices=[('parse_resume', '简历结构化解析'), ('analyze_position_resume', '岗位简历分析'), ('generate_regular_questions', '生成普通题'), ('generate_development_task', '生成开发题'), ('score_regular_submission', '普通题评分'), ('score_development_submission', '开发题评分'), ('generate_report', '生成报告'), ('export_document', '导出文档')], max_length=40, verbose_name='任务类型'),
        ),
    ]
